import { createOpenAI } from "@ai-sdk/openai";
import { generateText, Output } from "ai";
import { MemoryExtractionSchema } from "@kore/shared-types";
import type { MemoryExtraction } from "@kore/shared-types";

const SYSTEM_PROMPT = `You are a memory extraction engine for Kore, a personal knowledge management system.

Given raw text from a user's saved content, extract structured metadata as JSON.

## Rules
- Extract a concise, declarative title (not a sentence, but a name/label).
- Extract 1-7 atomic facts as standalone sentences. Each fact must be independently useful.
- Classify into exactly one QMD category path. Use ONLY these top-level roots:
  - qmd://tech/ (programming, hardware, software, frameworks)
  - qmd://travel/ (geography, restaurants, itineraries, tourism)
  - qmd://health/ (fitness, medical, recipes, nutrition)
  - qmd://finance/ (receipts, investing, budgeting, taxes)
  - qmd://media/ (books, movies, music, games)
  - qmd://personal/ (diary, relationships, goals, reflections)
  - qmd://admin/ (household, manuals, bureaucracy)
  You may add 1-2 sub-paths (e.g. qmd://travel/food/japan).
- Assign a type: "place", "media", "note", or "person".
- Generate 1-5 lowercase kebab-case tags.

## Example

Input: "John recommended Mutekiya in Ikebukuro for solo dining. Cash only, get the tsukemen. Usually a 30 min wait."

Output:
{
  "title": "Mutekiya Ramen",
  "distilled_items": [
    "Mutekiya is a ramen shop in Ikebukuro, Tokyo.",
    "Recommended by John for solo dining.",
    "Cash only.",
    "The tsukemen is the recommended order.",
    "Expect approximately a 30 minute wait."
  ],
  "qmd_category": "qmd://travel/food/japan",
  "type": "place",
  "tags": ["ramen", "ikebukuro", "solo-dining", "cash-only"]
}`;

/**
 * Create the Ollama-backed OpenAI-compatible provider.
 */
function createProvider() {
  const baseURL = process.env.OLLAMA_BASE_URL || "http://localhost:11434/v1";
  return createOpenAI({ baseURL, apiKey: "ollama" });
}

/**
 * Attempt to parse a MemoryExtraction from raw text response as a fallback
 * when structured output generation fails (e.g., model returns malformed JSON).
 */
export function fallbackParse(text: string): MemoryExtraction {
  // Try to find a JSON object in the text
  const jsonMatch = text.match(/\{[\s\S]*\}/);
  if (!jsonMatch) {
    throw new Error("Fallback parse failed: no JSON object found in response");
  }

  const raw = JSON.parse(jsonMatch[0]);
  return MemoryExtractionSchema.parse(raw);
}

/**
 * Extract structured memory metadata from raw text using a local LLM.
 *
 * Uses Vercel AI SDK's generateText() with Output.object() for Zod schema
 * enforcement, pointed at a local Ollama instance. Falls back to text-based
 * parsing if structured generation fails.
 */
export async function extract(
  rawText: string,
  source: string
): Promise<MemoryExtraction> {
  const provider = createProvider();
  const model = process.env.OLLAMA_MODEL || "qwen2.5:7b";

  try {
    const { output } = await generateText({
      model: provider(model),
      output: Output.object({ schema: MemoryExtractionSchema }),
      system: SYSTEM_PROMPT,
      prompt: `Source: ${source}\n\nRaw text:\n${rawText}`,
    });

    if (!output) {
      throw new Error("No structured output generated by model");
    }

    return output;
  } catch (primaryError) {
    // Fallback: attempt text-based generation and parse JSON from response
    try {
      const { text } = await generateText({
        model: provider(model),
        system: SYSTEM_PROMPT,
        prompt: `Source: ${source}\n\nRaw text:\n${rawText}\n\nRespond with ONLY valid JSON matching the schema.`,
      });

      return fallbackParse(text);
    } catch (_fallbackError) {
      // Re-throw the original error if fallback also fails
      throw primaryError;
    }
  }
}
